project:
  type: website
  
website:
  title: "Business Analytics, Data Science and Machine Learning Trends 2025"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Introduction"
      - href: data_cleaning.ipynb
        text: "Data Cleaning & Exploration"
      - href: eda.ipynb
        text: "Exploratory Data Analysis"
      - href: skill_gap_analysis.ipynb
        text: "Skill Gap Analysis"
      - href: ml_methods.ipynb
        text: "ML Methods"
      - href: nlp_methods.ipynb
        text: "NLP Methods"
format:
  html:
    theme: cosmo
    toc: true
execute:
  echo: true
  eval: true
  code-fold: true

project:
  type: website
