project:
  type: website

website:
  title: "ad688-employability-sp25A1-group13"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_analysis.qmd
        text: Data Analysis
      - about.qmd

format:
  html:
    theme:
      - lumen
      - brand
    css: styles.css
    toc: true



