project:
  type: website
  output-dir: _site
  
website:
  title: "Business Analytics, Data Science and Machine Learning Trends 2025"
  navbar:
    left:
      - href: index.html
        text: "Home"
      - href: about.html
        text: "About"
      - href: introduction.html
        text: "Introduction"
      - href: data_cleaning.html
        text: "Data Cleaning & Exploration"
      - href: eda.html
        text: "Exploratory Data Analysis"
      - href: skill_gap_analysis.html
        text: "Skill Gap Analysis"
      - href: ml_methods.html
        text: "ML Methods"
      - href: nlp_methods.html
        text: "NLP Methods"
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: true
    anchor-sections: true
    df-print: paged
execute:
  echo: true
  eval: true
  freeze: auto
resources:
  - figures/**

bibliography: references.bib
csl: csl/econometrica.csl
 

