project:
  type: website
  output-dir: docs
  
website:
  title: "ad688-employability-sp25A1-group13"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_analysis.qmd
        text: Data Analysis
      - href: about.qmd
        text: About 

format:
  html:
    theme: lux
    fontsize: 1.1em
    css: styles.css
    toc: true



