 project:
  type: website
  output-dir: docs
  
website:
  title: "ad688-employability-sp25A1-group13"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_analysis.qmd
        text: Data Analysis
      - href: about.qmd
        text: About Us


format:
  html:
    theme: lux
    fontsize: 1.1em
    css: styles.css
    toc: true

 on:
   push:
     branches: main

 name: Quarto Publish

 jobs:
   build-deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository
         uses: actions/checkout@v4

       - name: Set up Quarto
         uses: quarto-dev/quarto-actions/setup@v2

       - name: Install Python dependencies
         uses: actions/setup-python@v5
         with:
           python-version: '3.12'
       - run: pip install -r requirements.txt

       - name: Render and Publish
         uses: quarto-dev/quarto-actions/publish@v2
         with:
           target: gh-pages
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            